### PR TITLE
feat(theme-docs): add algolia integration (similar to vuepress)

### PR DESCRIPTION
**Pull request by lupas**
## Types of changes
- [X] New feature (a non-breaking change which adds functionality)

## Description
This PR adds Algolia DocSearch integration to the Docs theme, similar to how the folks at Vuepress do it.

Screenshot 2020-10-01 at 00 12 29

Screenshot 2020-10-01 at 00 38 45

## Checklist:
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes
  -> Not yet

## Try it out

1. Clone this branch
2. `cd packages/theme-docs && yarn && yarn link`
3. Clone the test branch [content-algolia](https://github.com/nuxt-community/firebase-module/tree/content-algolia) of the Nuxtjs/Firebase docs
4. `cd docs && yarn && yarn link @nuxt/content-theme-docs`
5. `yarn docs`

## Open ToDos:
This is a draft PR, so it is not yet finished. Anyone who would like to contribute is more than welcome. I'll continue soon.

The integration already works but has some minor issues to be fixed and especially needs some STYLING before we could merge it. (see also TODO's in code)

- [x] Optimize styling of the Algolia Dropdown incl. (1) specific styling for dark mode and (2) mobile-friendly styling
- [x] ~~Issue: `updateAlgolia()` for i18n language switch works BUT for some reason still displays the old dropdown field in addition~~
- [x] Change "From Version" in the docs

### CODE REVIEW

**Comment by lupas** [comment]
@Atinux I think proper search in Docs is quite important, would be cool if this could be merged at some point. 🙃

- I'm not that familiar with Nuxt styling guidelines, if you know s.o. who could fix up the styles that would be greatly appreciated.
- I thought about creating a separate component for the Algolia Search Bar, but the way the AppSearch component is currently structured that would have meant to either completely disassemble it. Let me know if you think it would be better to split it up in multiple components.

Cheers

**Comment by Atinux** [comment]
Hi @lupas 

Nice work on this, we will take a look at this with @benjamincanac :)

**Comment by benjamincanac** [comment]
Hey @lupas,

Really nice work, it's gonna be a game changer for all the docs out there!

I think it would be better to make two separate components for the search bar. I can do this and work on the styling part if you need help :)

**Comment by lupas** [comment]
@benjamincanac 
I agree, separate components would be much cleaner, and it would allow us to load the CSS & docsearch.js only in the Algolia component and not globally.

Didn't wanna break apart your existing component too much too, so I better asked first ;)

Yes please, if you have an idea on how to split it without generating too much redundant code I'd appreciate your help, and especially with the styling part ;)

I'll be busy until Friday but then for sure will finish this up on the weekend - my docs can't wait to get back their Algolia magic 😁

Thanks!

**Comment by benjamincanac** [comment]
@lupas I've updated the PR to make it work with the last version of Docsearch, I'm waiting for https://content.nuxtjs.org to be approved in the Docsearch program to merge this, but in the meantime tell me what you think :)

**Comment by lupas** [comment]
Wow, didn't even know there's a never version. This looks awesome! Thanks @benjamincanac 

Screenshot 2020-10-06 at 17 44 28

Also works like a charm with i18n and light/dark mode 👍

I noticed the following two things:

- [ ] ```facetFilters: [`tags:${lang}`]``` does not work for me while ```facetFilters: [`lang:${lang}`]``` works well. What was your intention there?  If we use tags, wouldn't we need to document how the Algolia Config should be set up?
- [x] ~~.DocSearch-Screen-Icon > svg is not centered:~~ (fixed with next commit)
Screenshot 2020-10-06 at 18 14 51

**Comment by benjamincanac** [comment]
@lupas Indeed it should be `lang` instead of `tags`, I used this to test it with the docsearch apiKey from nuxtjs.org. I'm still waiting for content approval to be able to test it.

**Comment by benjamincanac** [comment]
@lupas `@nuxt/content` has been added but noticed that the facet attribute is `language`: https://github.com/algolia/docsearch-configs/blob/master/configs/nuxtjs_content.json#L24.

Maybe this should be configurable?

**Comment by lupas** [comment]
> @lupas `@nuxt/content` has been added but noticed that the facet attribute is `language`: https://github.com/algolia/docsearch-configs/blob/master/configs/nuxtjs_content.json#L24.
> 
> Maybe this should be configurable?

For Nuxtjs_Firebase the Algolia team set it up with "lang"... So yes, I guess we would need to make that configurable.
https://github.com/algolia/docsearch-configs/blob/master/configs/nuxtjs_firebase.json

Guess we can take `language` as default (since yours has just been setup I guess they'll do it like this now).

I'm currently at work, in case you're busy I can do it later today.

**Comment by benjamincanac** [comment]
@lupas Just pushed and called it `langAttribute`, what do you think?

**Comment by lupas** [comment]
> @lupas Just pushed and called it `langAttribute`, what do you think?

Perfect, thanks! Just needs to be added to the docs too and then this is done 🥳

**Comment by benjamincanac** [comment]
@lupas It's done! Just waiting for the `nuxtjs_content` index to be filled, it should take 24 hours, and then it's good to go!

**Comment by lupas** [comment]
> @lupas It's done! Just waiting for the `nuxtjs_content` index to be filled, it should take 24 hours, and then it's good to go!

That's Awesome! Thanks a lot for getting this done so quickly!

**Pull request merged**
