### PR TITLE
feat(theme-docs): tags page

### LINKED ISSUE #357: [@nuxt/content-theme-docs] Add page for tags
Load tags from github, similar to releases

https://api.github.com/repos/:owner/:repo/tags

### PR DESCRIPTION
**Pull request by ricardogobbosouza**
Create page to tags

## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
Resolves #357 

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by benjamincanac** [comment]
@ricardogobbosouza Do you need Tags and Releases at the same time? I would only fetch tags if releases are missing.

**Comment by ricardogobbosouza** [comment]
@benjamincanac 
We can make this configurable in settings.json, what do you think?

**Comment by benjamincanac** [comment]
@ricardogobbosouza Indeed it would be nice :)

**Comment by benjamincanac** [comment]
Closing this for now as it hasn't been updated in a while. Feel free to reopen.

**Pull request closed without merging**
