### PR TITLE
docs: Translated docs into French

### PR DESCRIPTION
**Pull request by Nekika**
Tried to translate as better as I could, don't hesitate to ask for changes

### CODE REVIEW

**Comment by mathieunicolas** [comment]
haha, thanks ! I forked two days ago and I was about to start translating in french ! Perfect timing

**Comment by benjamincanac** [comment]
@Nekika Thanks for the PR! Could you also add french to the locales?

Thank you 😃

**Comment by Nekika** [comment]
@benjamincanac done ! :)

**Comment by Geminii** [comment]
@benjamincanac i think you merged it a little bit to faster. I was on review on it, and we can improve a lot of sentences. Some sentences contains careless mistakes ;)

**Comment by Nekika** [comment]
> @benjamincanac i think you merged it a little bit to faster. I was on review on it, and we can improve a lot of sentences. Some sentences contains careless mistakes ;)

You're right, I've just seen some mistakes that I'll fix asap.
If some sentences are not clear enough, don't hesitate proposing better ones ! :)

**Comment by benjamincanac** [comment]
@Geminii @Nekika Sorry about that! Thought it was done.

**Pull request merged**
