### PR TITLE
fix(theme-docs): improve live edit styles

### PR DESCRIPTION
**Pull request by ThomOrlo**
## Types of changes

- [X] Bug fix (a non-breaking change which fixes an issue) → **dark mode**
- [X] New feature (a non-breaking change which adds functionality) → **light mode**
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Before (light mode):
before-live-edit-light

Before (dark mode):
before-live-edit-dark

After (light mode):
after-live-edit-light

After (dark mode):
after-live-edit-dark

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by mathe42** [comment]
Great PR. I think you should add this styling directly in the editor.vue file. Your solution adds not used CSS to production build.

**Comment by ThomOrlo** [comment]
If I add this styling directly in the `editor.vue` file or` nuxt-content.dev.vue` file, it will be for everyone who uses `@nuxt/content`.
My proposal is just for `@nuxt/content-theme-docs`.

**Comment by benjamincanac** [comment]
@ThomOrlo It looks really nice! 
@mathe42 You're right, this shouldn't be defined in the `main.css` but it shouldn't be defined in `editor.vue` either, we can't use TailwindCSS classes in @nuxt/content. Do you have a suggestion on extending `nuxt-content-dev` component styles?

**Comment by Atinux** [comment]
I think it would be nice to use directly a custom editor for the docs theme directly (thanks to v1.7.0) so it could directly be used with custom css for it

**Comment by ThomOrlo** [comment]
Sorry I can't understand everything 😕 

From what I understood, `main.css` is injected globally:
https://github.com/nuxt/content/blob/dev/packages/theme-docs/src/index.js#L23
```js
css: [
  '~/assets/css/main.css'
],
```

For exemple `.filename`:
```css
& > .filename {
  @apply absolute right-0 top-0 text-gray-100 z-10 italic leading-none mr-3 mt-3;
}
```

These styles are visible on the final site :
explanations-main-style

With `.nuxt-content-editor`, it will work too, right?

**Comment by Atinux** [comment]
One way could be to add a main.dev.css and push it in development from the module to avoid including the css for editor or directly add the css in the nuxt-content.dev.js component

**Pull request merged**
