### PR TITLE
fix(transformers): opt-in to correct `extensions` spelling

### PR DESCRIPTION
**Pull request by harlan-zw**
### 🔗 Linked issue

Related https://github.com/nuxt/content/pull/1204#issuecomment-1146647579

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This is an alternative solution to the fix for mispelled extensions, this PR reverts the breaking change commit of  https://github.com/nuxt/content/pull/1204#issuecomment-1146647579. We prefer to use a soft breaking change to avoid having to bump majors.

I've also included a test for a custom transformer here using the deprecated key.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by harlan-zw** [comment]
Hm I wanted to revert the other commit but have done something wrong 😬

**Comment by harlan-zw** [comment]
Okay should be good

**Comment by Tahul** [comment]
That you a lot @harlan-zw 🙂

Should've renamed the original PR, this is my bad!

The new test is a great addition as well!

**Review by Tahul — APPROVED** [review]

**Comment by farnabaz** [comment]
I agree that no one yet used this feature, also we do not have good documentation about parsers and transformers.

Transformers are mainly used internally, We did not expose types and a helper to create custom transformers yet. So I see no harm in dropping misspelled key.

It will be good if we create/expose util to define transformers. like `defineContentTransformer`. This way we ensure users have full ts support and better DX

**Review by Tahul — CHANGES_REQUESTED** [review]
Could you please remove the `@deprecated` keys and support for previous implementation?

I would like to preserve the test-case there, but not the support for older implementations (point about this in discussion with @farnabaz above).

**Comment by harlan-zw** [comment]
I can make a seperate pr for the test case if not needed 👍

**Pull request closed without merging**
