### PR TITLE
feat(theme-docs): add variant and icon support in `list` component

### LINKED ISSUE #473: Option to specify a list type
### Is your feature request related to a problem? Please describe.
The current [list component](https://content.nuxtjs.org/themes/docs/#list) provides an easy way to display a visually appealing unordered list.

### Describe the solution you'd like
However, the default list includes green checkmarks. In scenarios where, for example, you want to show a list of things to be cautious about, it seems a bit odd to have green checks. It may be useful to consider the following options (while having similar color scheme as [alert component](https://content.nuxtjs.org/themes/docs/#alert)):
- info icon (bluish color - corresponding to info in alert component)
- warning triangle icon (yellowish color - corresponding to warning in alert component)
- cross icon (red color - corresponding to danger in alert component)

### Describe alternatives you've considered
It's obviously straightforward to build one's own component to achieve this functionality, but it seems like the logical step to have the default support a few other types.

### Additional context

If this is acceptable, I can attempt a pull request to add this enhancement.

### PR DESCRIPTION
**Pull request by sausin**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Resolves: #473

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by benjamincanac** [comment]
@sausin Thanks for the PR, I converted to draft while it's a WIP, mark it as ready for review once you're done 🙂

**Comment by sausin** [comment]
@benjamincanac will do, thanks :+1:

**Comment by sausin** [comment]
@benjamincanac Please have a look!

**Comment by benjamincanac** [comment]
@sausin Nice 🙂

**Comment by sausin** [comment]
@benjamincanac Thank you for the merge! Looking forward to using this in the next release :smiley:

**Pull request merged**
