### PR TITLE
feat(theme-docs): support rich category positioning

### PR DESCRIPTION
**Pull request by ndianabasi**
This request adds the ability to set the position of Categories along the App Navigation as rendered by AppNav.vue.

## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Ordering of the posts with the position property is not sufficient as it makes re-ordering the categories a nightmare for documentation sites with large numbers of posts. 

By setting an extra YAML property `categoryLevel` in the frontmatter of each post, it is possible to set exactly what level along the navigation each category should be rendered without having to re-order via the `position` property.

## Checklist:

- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by NozomuIkuta** [comment]
Related: #723

**Comment by ndianabasi** [comment]
@Atinux, please take a look at this. The check failed due to the prettier settings I use for my own development.

**Comment by ndianabasi** [comment]
> We have a better solution coming with the new theme (Docus) about ordering @ndianabasi
> 
> It is based directly on the file names, ex:
> 
> ```shell
> 1.top-category/
>   1.my-first-page.md
>   2.second-page.md
> 2.second-category/
>   1. first-page.md
> ```
> 
> This way, it keeps the same order in your filesystem/VSCode and on the website.
> 
> We plan to release Docus next week if everything goes smooth

Thank you. I will be looking forward to Docus. Well done.

**Comment by Tahul** [comment]
Hello, this feature is now fully implemented into both @nuxt/content v2 and Docus!

@nuxt/content. v1 has ordering and filtering features from file names.

You can find the documentation about this here: https://content-v2.nuxtjs.org/guide/writing-content/content-directory#ordering

That ordering is taken in account while building the navigation feature, that I think would solve that issue.

Docus takes advantage of that to render a complete navigation based on your project `content/` directory.

Feel free to re-open if want to continue the work on this PR!

Thank you for your contribution, I hope you'll like the new version! 🙂

**Comment by ndianabasi** [comment]
A big thank you to the team. ❤️❤️

**Pull request closed without merging**
