### PR TITLE
docs(content): add Vue components prop casing caveat

### PR DESCRIPTION
**Pull request by phivk**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

docs content tweak

## Description

Props of Vue component  in Markdown content need to use kebab name casing. This PR adds this caveat to the the documentation.

## Checklist:

- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by NozomuIkuta** [comment]
@phivk 

Hi, thank you for submitting a PR!

By the way, they seem to have changed the default branch to `v1` from `dev`, 
and consequently so many files which I believe are irrelevant are included as diffs.

So, would you change the target branch of this PR?
I think you can do it in PR edit view.

**Comment by phivk** [comment]
thanks @NozomuIkuta, I have updated this PR to use `nuxt:v1` as its base branch.
hope this helps :)

**Review by NozomuIkuta — COMMENTED** [review]
@phivk 

Thank you for changing the target (base?) branch.

I instantly tested camel-case and kebab-case prop in [CodeSandbox](https://codesandbox.io/s/nuxt-content-pr-1017-ckp8n8?file=/content/index.md), and your description is correct.

Before merging this PR, it's appreciated if you change the commit message to be semantic, according to the CI test. Would you change the commit message in your local and force-push it?

**Comment by Tahul** [comment]
Hey :)

I'm merging this as it could be useful for future documentation merges!

Thank you a lot for your contribution!

**Pull request merged**
