### PR TITLE
fix(theme-docs): Add updatedAt keypath to es-ES.js

### PR DESCRIPTION
**Pull request by cesaramirez**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Add missing keyPath to updatedAt in es-ES i18n translations

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Review by NozomuIkuta — CHANGES_REQUESTED** [review]
@cesaramirez 

Would you fix the lint error?

**Review by NozomuIkuta — APPROVED** [review]
@cesaramirez 

Thank you for fixing!

@pi0 

This PR is ready to be merged.

**Comment by cesaramirez** [comment]
Great!

**Comment by Tahul** [comment]
Thank, it'll most likely be useful to merge documentations between v1 and v2!

I'm merging this! 🙂

**Pull request merged**
