### PR TITLE
fix(theme-docs): Add updatedAt keypath to tr-TR.js

### PR DESCRIPTION
**Pull request by WoxeOfficial**
## Types of changes

- [X] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
Fixes the warning: "Fall back to translate the keypath 'article.updatedAt' with 'en' locale." when using tr locale.
https://imgur.com/a/6MQL8by

## Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Review by NozomuIkuta — APPROVED** [review]
Thank you for adding translation!

**Comment by WoxeOfficial** [comment]
I renamed commit.

**Comment by NozomuIkuta** [comment]
@WoxeOfficial 

Do you really want to close this PR?

If not, would you reopen so that I can request @pi0 to merge and release this PR.

**Comment by WoxeOfficial** [comment]
@NozomuIkuta Sorry but fork has already been deleted I can't reopen pr. If you guys want I can create a new pr.

**Comment by NozomuIkuta** [comment]
@WoxeOfficial
It's appreciated because this PR is helpful for speakers of the language. 🙏

**Pull request closed without merging**
