### PR TITLE
feat(content): improve reactivity

### LINKED ISSUE #519: Markdown data is not reactive
I'm trying to bind some data into v-model of my custom checkbox component and, when i'm trying to change v-model via clicking on checkbox, data does not updating.

### Version
@nuxt/content: v1.8.1
@nuxt/content-theme-docs: ex: v0.6.1
nuxt: v2.14.5

### Reproduction Link
https://codesandbox.io/s/nuxt-content-reactivity-issue-ev003

### PR DESCRIPTION
**Pull request by AlexanderBelokon**
Added reactivity support to bindings, event handling and v-model support for vue components

## Types of changes
- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
Allows content creators to use `@` and `v-on`, makes `:` and `v-bind:` reactive and allows to use `v-model` with custom components that use `value` field and emit `input` events with raw values (or emit `change` events and use `v-model` with `.lazy` modifier)
Resolves #519

## Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by benjamincanac** [comment]
@AlexanderBelokon Thanks a lot for this PR. Sorry for the delay, would you mind fixing the conflicts before we can review?

**Comment by AlexanderBelokon** [comment]
Sure, the conflict arose because the first commit of this PR was already merged as #685

**Comment by AlexanderBelokon** [comment]
Done! Thank you for your time and for such an awesome project!)

**Comment by Atinux** [comment]
Awesome work @AlexanderBelokon 💚

**Pull request merged**
