### PR TITLE
docs: add locale to content-docs and content-list

### PR DESCRIPTION
**Pull request by KhaledAlMana**
### 🔗 Linked issue
#1737 

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

```:locale``` was not documented to be used within ContentList, and ContentDoc but they works just fine and required for multilingual content.
#1737 

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by farnabaz** [comment]
`locale` props only exists and uses in `ContentQuery` component, And it is not defined in `ContentDoc` and `ContentList`.
It it only working because `ContentQuery` used as first child in other two components.
For now I suggest you to use `_locale` in `query` props alongside your  other `where`  options.

```vue
<ContentDoc :query="{where: [{_locale: 'fa'}]}" />
```

Later we may update components schema to officially support `locale` and other props

**Comment by KhaledAlMana** [comment]
> `locale` props only exists and uses in `ContentQuery` component, And it is not defined in `ContentDoc` and `ContentList`. It it only working because `ContentQuery` used as first child in other two components. For now I suggest you to use `_locale` in `query` props alongside your other `where` options.
> 
> ```
> <ContentDoc :query="{where: [{_locale: 'fa'}]}" />
> ```
> 
> Later we may update components schema to officially support `locale` and other props


Thank you @farnabaz for your response. 
In fact, I tried ```_locale``` same as your example, but it didn't work.
I keep getting 404. 
Find the snippet following your exmaple below for more info. 
``` const locale = 'ar-SA'; // en-US ```
```
    <ContentDoc
      :query="{
        where: [{ _locale: locale }], 
      }"
    >
      <template #default="{ doc }">
        <!-- {{ content }} -->
        <PageHeader>
          <PageTitle :text="doc.title" />
        </PageHeader>
        <PageBody>
          <PageSection>
            <ContentRenderer :value="doc" />
          </PageSection>
        </PageBody>
      </template>
      <template #empty>
        <h1>Post in empty</h1>
      </template>
      <template #not-found>
        <Error :code="404" wrap />
      </template>
    </ContentDoc>
```

**Comment by farnabaz** [comment]
This is strange, this is how ContentQuery treat with locale: https://github.com/nuxt/content/blob/d475afe4c3e13ca25d9f4299b186e19879fa9f46/src/runtime/components/ContentQuery.vue#L128

Could you provide a simple reproduction using [Stackblitz starter](stackblitz.com/github/nuxt/starter/tree/content)?

**Comment by KhaledAlMana** [comment]
Indeed it is strange.
I did already a reproduction linked to the issue #1737  
https://stackblitz.com/edit/github-jzx7nq

**Comment by KhaledAlMana** [comment]
I have been trying to do it again - upon your example. 

This way worked find. However, I have to mention path towice. If one is removed locale won't be working. 
```
    <ContentDoc
      :head="true"
      :path="$route.path"
      :query="{
        where: { _path: { $eq: $route.path }, _locale: locale },
        }"
    >
``` 

I'm kinda confused now, I think query works just find and locale but the problem is with path not locale?

**Comment by farnabaz** [comment]
Thank you, @KhaledAlMana 
I'm closing this PR and reopening your issue, the issue is not about the components, but it lays in query builder and Content's indexing system

**Pull request closed without merging**
