### PR TITLE
docs: Translated theme documentation and removed old file

### PR DESCRIPTION
**Pull request by cogor**

### CODE REVIEW

**Comment by benjamincanac** [comment]
Hey @cogor, we've improved the documentation on the docs theme again in #330, sorry 😅

Should I merge this or wait?

BTW thanks for keeping up the translation in Russian up-to-date!

**Comment by cogor** [comment]
Wait, I will update it

**Comment by cogor** [comment]
Done

**Comment by benjamincanac** [comment]
@cogor Could you rebase the `dev` branch so the PR contains only the actual file changed?

**Comment by cogor** [comment]
It seems to be ready.
😅 sorry, I'm not very good know git

**Comment by benjamincanac** [comment]
It seems that the merges broke something I can't rebase it. Would you mind opening a new PR?

**Comment by cogor** [comment]
Yep, of cource

**Pull request closed without merging**
