### PR TITLE
feat(content/theme-docs): support surround by path

### PR DESCRIPTION
**Pull request by NozomuIkuta**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Resolves: #658. 

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by NozomuIkuta** [comment]
Oops, I've found that this PR includes breaking change...renaming argument... (i.e. `slug` to `slugOrPath`)

Should I revert the name to `slug` and let the method accept path string as well? Or should I create another method like `surroundByPath()`?

**Comment by NozomuIkuta** [comment]
Naming may be an issue in terms of API body.
So, another alternative would be accepting both `slug` and `path` and checking which is passed.

**Comment by Atinux** [comment]
Thank you for this great PR @NozomuIkuta 

I don't think renaming is really a breaking change since people use `$content` and not directly making API call to `/_content`  endpoint.

I am good with this PR, maybe @benjamincanac might see stuff that I don't see.

**Review by benjamincanac — APPROVED** [review]

**Comment by benjamincanac** [comment]
@NozomuIkuta Thanks for this, I'm aware that it's been a bit complicated to implement the surround when working with sub-directories.

**Pull request merged**
