### PR TITLE
docs(content): Russian documentation update

### PR DESCRIPTION
**Pull request by Roman86**
## Types of changes
- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

adds missing configuration keys to the Russian documentation: `githubApi`, `defaultDir` and `algolia` options described

## Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Review by NozomuIkuta — COMMENTED** [review]
@Roman86 

Thank you for the PR!

Sorry for late review. 🙏
It has been for few months and there might be changes in the original content.
Would you take a look at the latest English content again just in case?

Once you let me know there is no update or you update the Russian content, I will merge your PR.

**Comment by Roman86** [comment]
@NozomuIkuta no problem! Thanks for getting in touch. Sure, I'll check and update accordingly. Will get back to you once done.

**Comment by Roman86** [comment]
@NozomuIkuta ok, I've reviewed every single sentence in that theme docs russian file, comparing it with the latest [english](https://github.com/nuxt/content/blob/main/docs/content/en/themes/docs.md) one from the main branch - added a few missing sections, updated the markup in some places, added versions badges, new options, props etc.

**Review by NozomuIkuta — APPROVED** [review]
@Roman86 

Thank you for confirmation!

I translated your script to English with Google Translation and compare it with the original one.
There seems to be no different than wording, as far as I see.

Because I'm not a Russian speaker, I believe it's better to leave further review and update to other Russian speakers. 🙌 

Let me merge this PR right now. 👍

**Comment by Roman86** [comment]
yes, it's translated very carefully, no machine translation was used. Finally, it covers all the original topics, many were missing

**Pull request merged**
