### PR TITLE
feat: add content:file:beforeParse hook

### PR DESCRIPTION
**Pull request by mathe42**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

see #432 
alternative / addition? to #450 

Example:
```ts
hooks: {
  'content:file:beforeParse': (file) => {
    if (file.extension !== '.md') return
    file.data = preParser(file.data)
  }
}
```

## Checklist:

- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

## ToDos
- [ ] Docs
- [ ] tests

### CODE REVIEW

**Comment by Atinux** [comment]
Thanks for the PR @mathe42 

I think `content:file:parsed:after` is not needed since we have `content:file:beforeInsert` which is right after the parsing.

I would also rename `content:file:parsed:before` to `content:file:beforeParse`

**Comment by Atinux** [comment]
This looks good to me, one thing I am thinking might be to rename `file` to `text` or `body`, cc @benjamincanac

**Comment by mathe42** [comment]
You mean in line 174?
https://github.com/nuxt/content/blob/507f13baa54d57891ca1a543c710b0bbac1fea90/packages/content/lib/database.js#L173-L175

**Comment by Atinux** [comment]
Hi @mathe42 

I renamed to use `file` and `file.data`.

It looks good to me now, only thing left is to add this hook in the docs: https://content.nuxtjs.org/advanced#hooks

**Review by Atinux — APPROVED** [review]

**Pull request merged**
