### PR TITLE
fix(docs): minor capitalization fix

### PR DESCRIPTION
**Pull request by skepfusky**
Minor documentation change

## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

There are some capitalization issues I've changed; from "nuxt" to "Nuxt" and "typescript" to "TypeScript" from the Installation page I found while reading through the docs.

## Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by NozomuIkuta** [comment]
@skepfusky 

Hi, thank you for submitting a PR!

It's appreciated if you make the commit message semantic as CI test warns.
The PR title, `docs(content): minor capitalization fix`, looks good to me.

**Comment by skepfusky** [comment]
Ah, sorry about that! I'm relatively new to contributing OS projects like these. 😅

**Comment by NozomuIkuta** [comment]
@skepfusky 

Oh, sorry for my lack of words. 🙏 
I meant I would like you to change the commit message instead of PR title (making them consistent in other words). 
Ref: https://linuxize.com/post/change-git-commit-message/

**Comment by skepfusky** [comment]
Apologies for the late response, but I changed the commit message and all checks have been passed!

**Comment by NozomuIkuta** [comment]
@skepfusky 

No apology is needed.
Thank you for contribution!😄

**Pull request merged**
