### PR TITLE
feat: add yarn v2 (berry) support

### PR DESCRIPTION
**Pull request by mathe42**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

This PR adds yarn v2 support. For this the json5 dependencie has to be added directly in package.json

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by mathe42** [comment]
As json5 is required by some code with yarn v2 @nuxt/content has to declare it in the dependencies.

This is a single line change to the package.json

Just wondering why is yarn.lock not in git and not in .gitignore? One of this should be true!?

**Review by NozomuIkuta — COMMENTED** [review]
@mathe42 

Would you share some references so that we can know better why `json5` package is needed?
Once it's verified, I think I can merge this PR.

By the way, `yarn.lock` was generated again after you had created this PR.
So it would be safer if you merge the main branch to your branch and update `yarn.lock` file as needed.

**Comment by mathe42** [comment]
JSON5 is imported here: https://github.com/nuxt/content/blob/main/packages/content/lib/database.js#L5 so for yarn v2 (berry) it would be optimal to add it to dependencies. (You can have multiple versions of a package with yarn v2 so yarn doesn't know wich to use. (There are workarounds but I think adding the dependencie would be a good idea).

**Review by NozomuIkuta — APPROVED** [review]
@mathe42 

Thank you for quick response!

I see, and yeah, JSON5 package definitely should be added as a dependency if it's directly used by the package, regardless of Yarn's requirement. 🙌

**Pull request merged**
