### PR TITLE
docs: updated integrations with more information #425 #386

### LINKED ISSUE #386: generate sitemap.xml
### Is your feature request related to a problem? Please describe.
`@nuxtjs/sitemap` can generate a sitemap dynamically by specifying the `routes` option.
But `@nuxt/content` doesn't support sitemap generation.

### Describe the solution you'd like
Update `sitemapOptions` on the occurrence of the `sitemap:generate:before` event.
https://github.com/nuxt-community/sitemap-module#hooks

Here's a sample code.
https://github.com/odanado/blog/blob/8ca87f3dc63477d870f09b24b115cd25f3cd8996/app/modules/sitemap.ts

### LINKED ISSUE #425: Generate HTML for RSS Feed content property
I'm working on my RSS feed for my blog. Things are going great, but I've got a hangup.

I want to generate the content for my blog in the content property for the RSS feed, however I'm using a mix of markdown and vue components in my .md files. 

Using the existing methods I can generate the JSON AST or simply pass in the markdown content with no problems, but getting the Vue components to render as html is another hurdle. 

Sure, I could go through my blog posts and remove the Vue components but where's the fun in that?

So I've been thinking about how to do this and wondering if nuxt/content has an API or something that already does what I need and I just missed it. 

Anyway, here is the relevant piece of nuxt.config.js for reference, I've defined my create function to be reused

(btw this version is friendly with `nuxt generate` which your version in the Integrations section does not seem to be - I get an error when I use your version with `nuxt generate` but I plan to simplify this and update your docs with this alternate version)

```
const create = async (feed) => {
  feed.options = {
    title: "James MacIvor's Blog",
    description: "Technology, Business, Teaching and Mentoring",
    link: process.env.NODE_ENV === 'production' ? 'https://www.macivortech.com/feed.xml' : 'localhost:3000/feed.xml'
  }

  // eslint-disable-next-line global-require
  const { $content } = require('@nuxt/content')
  if (posts === null || posts.length === 0)
    posts = await $content('blogs').fetch()

  posts.forEach((post) => {
    const url = process.env.NODE_ENV === 'production' ? `https://www.macivortech.com/blog/${post.slug}` : `localhost:3000/blog/${post.slug}`
    feed.addItem({
      title: post.title,
      id: url,
      link: url,
      description: post.description,
      content: post.stuff
    })
  })
}

export default {
...
  modules: [
    'nuxt-svg-loader',
    '@nuxtjs/dotenv',
    '@nuxt/content',
    '@nuxtjs/feed'    
  ],

  feed: [
    {
      path: '/feed.xml',
      create,
      cacheTime: 1000 * 60 * 15,
      type: 'rss2'
    },
    {
      path: '/feed.json',
      create,
      cacheTime: 1000 * 60 * 15,
      type: 'json1'
    }
  ],

  hooks: {
    'content:file:beforeInsert': async (document) => {
      // *do magic stuff here*
      const html = doTheMagic(document)

        document.html= html;
      }
    }
  },
...
}
```

I'm definitely learning some new stuff here - but I think I can accomplish this using a workflow like this:

In the hook: 'content:file:beforeInsert':

1. Create a dummy Vue instance
2. Use your existing render function NuxtContent //or something, not sure I want to create the entire unified md to html process here, but if I have to?
3. Pass in the document
4. Use a Vue SSR process (??really uncertain about this??) to resolve the Vue Components
5. Append the resulting html to the document
6. Pull the html into the feed content property in the create function

So the question, does my goal make sense? (I don't typically mess with RSS so I'm learning as I go)
Does the challenge I'm outlining make sense?
Can you give me some guidance on my suggested plan? 

Thanks

### PR DESCRIPTION
**Pull request by RobotOptimist**
## Types of changes

- [x ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
The existing documentation for integrating with nuxt/feed does not work when statically generating pages. Also, it does not include a process for getting all of the content for the content field of the feed. This change will provide that missing information. This change also adds a process for integrating with nuxt/sitemap. Closes #425 Closes #386

## Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by RobotOptimist** [comment]
Also closes #386

**Comment by benjamincanac** [comment]
Thank you @RobotOptimist, this section will be really helpful!

**Comment by narduin** [comment]
Hi!

In the sitemap section, is `posts` supposed to be defined as a variable somewhere or is it a native element?
I'm getting an error `posts is not defined` when trying the snippet.

Thanks a lot!

**Comment by RobotOptimist** [comment]
Hi @narduin, sorry about that - I had it defined as a separate variable in a previous example

```
let posts = [];
```

**Pull request merged**
