### PR TITLE
feat: add user defined parsers

### LINKED ISSUE #104: Parser plugin interface
### Is your feature request related to a problem? Please describe.

A few days ago I submitted a request (#67) for a parser for .txt files. I've also been pondering a parser for SVG files to solve a problem with avatars. 

Today I started studying the [parser code](https://github.com/nuxt/content/tree/master/lib/parsers). I see that the CSV and YAML parsers are both very simple: a class definition with a `toJSON` method, with modules handling the heavy work. 

### Describe the solution you'd like

A configuration point in `nuxt.config.js` for custom parsers. It could be as simple as an array of patterns and resolution functions:
```
[
    {
        'pattern': /^\.txt$/,
        'parse': function (file) {
            return file.split('\n');
        }
    }
]
```

### Describe alternatives you've considered

I don't know that there is any real alternative to this at this point. I've searched both the documentation and the code for information about custom parsers and haven't found any information.

### PR DESCRIPTION
**Pull request by mathe42**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [X] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Add option to add UserDefined parsers:

```js
{
   content: {
     extendParser: {
        '.myfile': file => parse(file)
     }
   }
}

```

fixes #104 

## Checklist:

- [X] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by mathe42** [comment]
@benjamincanac added docs. Can you help me with tests?

**Comment by Atinux** [comment]
Thank you for the PR, I think we should rename `userParser` to `extendParser` instead.

**Comment by mathe42** [comment]
@Atinux Done.

Build fails in macos for no reason (while `yarn` connection is lost.) A rerun should fix that.

**Comment by Atinux** [comment]
Awesome :)

On thing left is to add a test with a custom parser!

**Comment by mathe42** [comment]
Yes. But I need help with this... Don't know where to start...

**Comment by Atinux** [comment]
@benjamincanac can you help him on the tests onboarding?

**Comment by benjamincanac** [comment]
Hey @mathe42, I've just pushed a test in `test/options.test.js`, I guess this should be enough, what do you think @Atinux?

**Comment by mathe42** [comment]
Looks good to me.

**Pull request merged**
