### PR TITLE
fix(theme-docs): revert @tailwindcss/typography bump

### PR DESCRIPTION
**Pull request by NozomuIkuta**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Resolves: #826
Resolves: #863

This PR is revert bump of `@tailwindcss/typography` caused by Renovate app.

By the way, I found that @benjamincanac once had applied [the same fix](5adf1a295d1c33cbac3a6ea7a3ae32e94a73f9c7) in the past just before Theme Docs v0.10.0 was released.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

I checked UI in my local as much as possible.
I believe this change will fix the broken UI with Theme Docs v0.10.2.

### CODE REVIEW

**Review by Atinux — APPROVED** [review]

**Comment by NozomuIkuta** [comment]
@Atinux 

Would you merge this PR?
 It seems that I don't have permission to do it.

Once you merged this PR, I will publish the `main` branch as soon as possible, but give me 24 hours. 🙏 
(I mean, it's over 3 a.m. in my place, Japan.)

**Comment by Atinux** [comment]
I re-run the CI, one of them si failing.
You shall be able to merge now @NozomuIkuta

**Comment by NozomuIkuta** [comment]
@Atinux 

Thank you, now I see the button and am going to merge the PR!!

---

By the way, I might have missed the Squash and merge button in the box below last night.
I guess I was looking for it below the comment text area. 😅

**Comment by NozomuIkuta** [comment]
@pi0 

Now I'm ready to publish the package in my side!

I'm looking forward to your contact on Discord or Twitter. 🙋‍♀️ 
Atinux said it to me yesterday that you would.

**Comment by WolfgangDrescher** [comment]
Is this fix already released? Using a fresh installation with `npm init nuxt-content-docs` im still experiencing the same issue as in #826. `@nuxt/content-theme-docs` is set to `v0.10.1` in the package.json if that is relevant.

**Comment by NozomuIkuta** [comment]
@WolfgangDrescher 

Unfortunately, not yet.

@pi0 

How about cutting the release tag to release this PR that has a big impact?

**Pull request merged**
