### PR TITLE
feat: add XML support

### PR DESCRIPTION
**Pull request by mathe42**
adding Support for XML files

### CODE REVIEW

**Comment by benjamincanac** [comment]
Hey @mathe42, 

Thanks for this PR!

Could you also:

- [ ] add in `example/content` an XML file to demonstrate like the other formats in `example/pages/index.vue`
- [ ] add in `test/fixture/content/formats` an XML file to ensure parsing works
- [ ] add in `docs/content/en/writing.md` a section about XML format

**Comment by mathe42** [comment]
Jap. Will work on that.

**Comment by mathe42** [comment]
@benjamincanac 
All done.

**Comment by benjamincanac** [comment]
Actually there are still tiny things missing:

- [ ] In `docs/en/configuration.md`, could you add a section like for the yaml: https://content.nuxtjs.org/configuration#yaml
- [ ] In `lib/utils.js`, could you add `xml` to the defaults

**Comment by mathe42** [comment]
I can nearly switch to any xml Parser I will look into https://github.com/Leonidas-from-XIV/node-xml2js

**Comment by mathe42** [comment]
@benjamincanac Now it should work. I changed the parser.

**Comment by mathe42** [comment]
Documentiation is updated.

**Comment by benjamincanac** [comment]
@mathe42 Perfect! Thanks 😃

**Pull request merged**
