### PR TITLE
docs: use lowercase typings, use `|` instead of `or` in type declaration

### PR DESCRIPTION
**Pull request by nobkd**
### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

Other declarations follow the same schema.

### CODE REVIEW

**Comment by nobkd** [comment]
I've also seen that sometimes the types begin with a capital letter and sometimes they don't.

E.g. here
https://github.com/nuxt/content/blob/2ee6de5cae3285d2fc30e72ef533d7e22a06f973/docs/content/4.api/3.configuration.md#L404-L412
See `Boolean` vs `boolean`.
This also happens with other default types.

I think they should all use **lowercase** letters, as that's the way they're used in code.

The types I talk about are `number`, `string`, `boolean`, `object` etc. and their array variants.

What do you think?

**Review by Atinux — APPROVED** [review]

**Comment by Atinux** [comment]
Ok for me to have all lowercase, happy to update it on this PR?

**Comment by nobkd** [comment]
Sure. Will do that

**Comment by nobkd** [comment]
I updated the typings for Content v2 now.
Should I change them for v1 too?

**Review by farnabaz — APPROVED** [review]
Thanks 👍

**Comment by farnabaz** [comment]
> Should I change them for v1 too?

It would be great if you do so 👍

**Comment by farnabaz** [comment]
Thanks @nobkd ❤️

**Pull request merged**
